import Image from 'next/image'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import Navbar from '@/components/Navbar'
import Main from '@/components/Main'
import About from '@/components/About'
import Skills from '@/components/Skills'
import Projects from '@/components/Projects'
import Contact from '@/components/Contact'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className="px-5">
      <Head>
        <title>Kavindu Sayuranga</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/assets/logo.png' />
      </Head>
      <Main className="mb-20"/>
      <About/>
      <Skills/>
      <Projects/>
      <Contact/>
    </div>
  )
}
